### ISSUE TITLE
Unexpected error when installing dapp-runner with pip in empty virtualenv

### ISSUE THREAD

**Issue by lucekdudek** [golemfactory/dapp-runner#98]
Name: Cannot install dapp-runner
OS+lang+version (if applicable): ubuntu 22.04 python 3.9.16
Title: when running `pip install dapp-runner`
during [https://golem-network.gitbook.io/golem-sdk-develop/requestor-tutorials/dapps/hello-world-dapp](https://golem-network.gitbook.io/golem-sdk-develop/requestor-tutorials/dapps/hello-world-dapp) `Hello world -  Run the app` cannot install `jsonrpc-base`
    
```
    $ pip install dapp-runner
    ...
    Building wheels for collected packages: jsonrpc-base
      Building wheel for jsonrpc-base (setup.py) ... error
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [49 lines of output]
    ...
    Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
    ...
            File "/home/lucjan/.pyenv/versions/3.9.16/lib/python3.9/distutils/cmd.py", line 103, in __getattr__
              raise AttributeError(attr)
          AttributeError: install_layout
          [end of output]
    ...
    note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for jsonrpc-base
      Running setup.py clean for jsonrpc-base
    Failed to build jsonrpc-base
    ...
    note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> jsonrpc-base
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
```

install-dapp-runner.log file can be found here https://www.notion.so/golemnetwork/dapps-testing-session-3-9905e19a88284b44931a9519c1159324

Error occurred on different OS

**Comment by shadeofblue** [comment]
a quick glance at search results suggests this to be some issue with an outdated `setuptools` installation...
